# Generated by Django 4.1 on 2023-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
