# Generated by Django 4.1 on 2023-10-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
